In [41]:
# NumPy stands for Numerical Python. NumPy is a Python library used for working with arrays. The array object in NumPy is called ndarray. 
# In Python lists are use to serve the purpose of arrays which are slow to process.
# NumPy provides an array object which is faster than traditional Python lists.
# NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
# NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.
# The source code for NumPy is located at this github repository https://github.com/numpy/numpy.

In [40]:
#Array and shape 1D Array
import numpy as np
cpu_usage = np.array([42,55,78,91,63])
print(cpu_usage)
print("type of object:", type(cpu_usage))
print("shape", cpu_usage.shape)
print("dtype", cpu_usage.dtype)

[42 55 78 91 63]
type of object: <class 'numpy.ndarray'>
shape (5,)
dtype int64


In [25]:
#2D ARRAYS - 3 servers x 5 time steps
metrics = np.array([
    [42,55,78,91,63], 
    [30,35,40,38,45],
    [88,92,95,97,99] ])
print("shape", metrics.shape)
print("ndim", metrics.ndim)

shape (3, 5)
ndim 2


In [26]:
# Array dimension
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([
              [1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9],
              [10,11,12]
             ])

d = np.array([
                [[1, 2, 3], [4, 5, 6]], 
                [[1, 2, 3], [4, 5, 6]]
])
e = np.array([[1, 2, 3], [4, 5, 6]])
f = np.array([
                [[1, 2, 3], [4, 5, 6],[7, 8, 9]], 
])
print("a-ndim", a.ndim)
print("b-ndim", b.ndim)
print("c-ndim", c.ndim)
print("d-ndim", d.ndim)
print("e-ndim", e.ndim)
print("f-ndim", f.ndim)

a-ndim 0
b-ndim 1
c-ndim 2
d-ndim 3
e-ndim 2
f-ndim 3


In [27]:
import numpy as np

# 1. 1D array of memory usage (in %) for 6 time steps:
memory = np.array([60,65,70,68,85,90])

# 2. Print shape, ndim, and dtype. these are attributes..doesnt have ()
print(memory.shape)
print(memory.ndim)
print(memory.dtype)

# 3. 2D array with 2 servers and 4 readings each:

servers = np.array([
    [50,60,55,70], 
    [80,85,90,88],
])

# 4. shape of servers 
print(servers.shape)

# 5. Array of 6 evenly spaced alert thresholds between 50 and 100
thresholds = np.linspace(50,100,6)
print(thresholds)
print(thresholds.dtype)

(6,)
1
int64
(2, 4)
[ 50.  60.  70.  80.  90. 100.]
float64


In [28]:
scores = [24,25,27,90,67,88]
print(scores)  # prints a list with commas

[24, 25, 27, 90, 67, 88]


In [29]:
import numpy as np
scores = np.array(scores)
print(scores)   # prints an array, no commas..declaread as an array in line above
# Print min, max, mean, sum , std . these are methods..have ()
print(scores.min())
print(scores.max())
print(scores.mean())
print(scores.sum())
print(scores*2)

[24 25 27 90 67 88]
24
90
53.5
321
[ 48  50  54 180 134 176]


In [30]:
import numpy as np
cpu = np.array([45,58,78,90])
print(cpu)
print("shape:", cpu.shape)
print("min value:", cpu.min())
print("max value:", cpu.max())
print(cpu*2)
print("Mean:", cpu.mean())     # Average
print("Above 70:", cpu > 70)   # Boolean mask — which scores are above 70
print("Above 70", cpu[cpu>70]) # Gives the value where condition is true
print("belwo 70", cpu[cpu<70])

[45 58 78 90]
shape (4,)
min value 45
max value 90
[ 90 116 156 180]
Mean: 67.75
Above 70: [False False  True  True]
Above 70 [78 90]
belwo 70 [45 58]


In [32]:
import numpy as np

# Each row is a student, each column is a subject
marks = np.array([
    [45, 78, 90],   # shiva
    [58, 82, 76],   # john
    [92, 88, 95],   # marry
    [98, 74, 88]    # ram
])

# 1 - print shape
print("Shape:", marks.shape)  

# 2 - average score of each student (row wise)
print("Student averages:", marks.mean(axis=1).round(1))  

# 3 - average score of each subject (column wise)
print("Subject averages:", marks.mean(axis=0).round(1))   

Shape: (4, 3)
Student averages: [71.  72.  91.7 86.7]
Subject averages: [73.2 80.5 87.2]


In [33]:
import numpy as np
cpu = np.array([
    [45,65,98],
    [67,37,88],
    [87,48,79]
    ])

print(cpu)
print("shape", cpu.shape)
print("cpu average server wise", cpu.mean(axis = 1).round(1))         # row wise - server wise mean
print("cpu average minute wise", cpu.mean(axis = 0).round(1)) # column wise - minute wise mean

[[45 65 98]
 [67 37 88]
 [87 48 79]]
shape (3, 3)
cpu average server wise [69.3 64.  71.3]
cpu average minute wise [66.3 50.  88.3]


In [34]:
# Dataset — 5 students, 3 subjects (Math, Science, English)
import numpy as np
marks = np.array([
    [45, 78, 90],
    [58, 82, 76],
    [92, 88, 95],
    [98, 74, 88],
    [40, 55, 60]
])

print("shape", marks.shape)
print("average of each student", marks.mean(axis = 1))
print("average of each subject", marks.mean(axis = 0))
print("highest scored in the entire database", marks.max())
print("gives true or false for the conditions student average > 80", marks.mean(axis=1)>80) #boolean mask
print("students scored above 80 average", marks[marks.mean(axis=1)>80])  #boolean masking for dataframe, only prints where condition is true.
print("multiply", marks*1.1)

shape (5, 3)
average of each student [71.         72.         91.66666667 86.66666667 51.66666667]
average of each subject [66.6 75.4 81.8]
highest scored in the entire database 98
gives true or false for the conditions student average > 80 [False False  True  True False]
students scored above 80 average [[92 88 95]
 [98 74 88]]
multiply [[ 49.5  85.8  99. ]
 [ 63.8  90.2  83.6]
 [101.2  96.8 104.5]
 [107.8  81.4  96.8]
 [ 44.   60.5  66. ]]


In [35]:
#Dataset - 5 servers, 6 time steps for cpu_metrics
import numpy as np
cpu_metrics = np.array([
    [84, 87, 90, 83, 94, 150],   
    [78, 57, 78, 56, 89, 91],
    [56, 74, 46, 58, 69, 79],
    [87, 76, 65, 54, 94, 160],   
    [60, 62, 61, 59, 63, 64]
])
print(cpu_metrics)
print("shape:", np.shape(cpu_metrics))
print("shape:", cpu_metrics.shape)  
print("average of all server cpu readings-global:", cpu_metrics.mean().round(1))
print("standard deviation of all servers-global:", cpu_metrics.std().round(1))
print("average of each server: \n ", cpu_metrics.mean(axis=1).round(1))  #server wise
print("average of all servers at particular time: \n :", cpu_metrics.mean(axis=0).round(1))  #time wise for all servers
print("high cpu among all servers: \n ", cpu_metrics.max())
print("servers with above 80 average: \n ", cpu_metrics[cpu_metrics.mean(axis=1) >80]) 
print("multiply server metrics with 1.1: \n", cpu_metrics * 1.1)

[[ 84  87  90  83  94 150]
 [ 78  57  78  56  89  91]
 [ 56  74  46  58  69  79]
 [ 87  76  65  54  94 160]
 [ 60  62  61  59  63  64]]
shape: (5, 6)
shape: (5, 6)
average of all server cpu readings-global: 77.5
standard deviation of all servers-global: 24.8
average of each server: 
  [98.  74.8 63.7 89.3 61.5]
average of all servers at particular time: 
 : [ 73.   71.2  68.   62.   81.8 108.8]
high cpu among all servers: 
  160
servers with above 80 average: 
  [[ 84  87  90  83  94 150]
 [ 87  76  65  54  94 160]]
multiply server metrics with 1.1: 
 [[ 92.4  95.7  99.   91.3 103.4 165. ]
 [ 85.8  62.7  85.8  61.6  97.9 100.1]
 [ 61.6  81.4  50.6  63.8  75.9  86.9]
 [ 95.7  83.6  71.5  59.4 103.4 176. ]
 [ 66.   68.2  67.1  64.9  69.3  70.4]]


In [36]:
#combining into single dataset
import numpy as np

# CPU usage for 3 servers
cpu = np.array([60, 75, 90])

# Memory usage for same servers
memory = np.array([70, 65, 95])

# Combine into single dataset
metrics = np.array([cpu, memory])

print(metrics)

[[60 75 90]
 [70 65 95]]


In [37]:
# 3D data → servers × time × metrics
data = np.random.randint(30, 100, size=(5, 10, 2))  #5 servers, 10 time stamps, 2 metrics( cpu, ram)
print("shape", data.shape)
print("ndim", data.ndim)
print("dtype", data.dtype)
print(data)

shape (5, 10, 2)
ndim 3
dtype int32
[[[35 78]
  [60 59]
  [82 81]
  [92 97]
  [45 41]
  [98 71]
  [90 56]
  [68 38]
  [39 36]
  [52 30]]

 [[36 74]
  [86 76]
  [46 94]
  [56 36]
  [78 47]
  [39 38]
  [45 78]
  [56 65]
  [43 74]
  [34 39]]

 [[44 39]
  [91 59]
  [50 89]
  [46 81]
  [44 58]
  [75 40]
  [55 32]
  [77 56]
  [81 43]
  [93 77]]

 [[70 61]
  [83 99]
  [90 72]
  [99 82]
  [61 84]
  [82 55]
  [90 40]
  [46 81]
  [55 52]
  [39 92]]

 [[81 33]
  [80 77]
  [62 73]
  [33 34]
  [34 68]
  [58 37]
  [63 44]
  [63 55]
  [78 49]
  [39 40]]]
