In [1]:
#1D INDEXING - SINGLE VALUES
import numpy as np
cpu = np.array([42, 55,78,91,63])
print(cpu[0])
print(cpu[1])
print(cpu[3])
print(cpu[-1])
print(cpu[-2])

42
55
91
63
91


In [3]:
#1D slicing - range of values # [start : stop : step]
cpu = np.array([42,55,78,91,63])
print(cpu)
print(cpu[1:4])
print(cpu[:3]) # upto 3 index 0,1,2
print(cpu[2:]) # from 2nd index onwards
print(cpu[::2]) # every 2nd element

[42 55 78 91 63]
[55 78 91]
[42 55 78]
[78 91 63]


In [7]:
#2D indexing - rows and columns  [row,column]
servers = np.array([
    [42,55,78,91,63],  #row 0 - server A
    [30,35,40,38,45], # row 1 - server B
    [88,92,95,97,99] # row2 - server C
])
print(servers[0]) # server A
print(servers[1]) # server B
print(servers[0,3]) # servera A 4th reading
print(servers[2,-1]) # server c last reading

[42 55 78 91 63]
[30 35 40 38 45]
91
99


In [11]:
#2D slicing - subsets of the grid
print(servers[:, 2:]) # all rows(servers), column 2nd reading onwards
print(servers[:2, :]) # first 2 servers all readings
print(servers[:, 1]) # all rows(Servers), 2nd reading only

[[78 91 63]
 [40 38 45]
 [95 97 99]]
[[42 55 78 91 63]
 [30 35 40 38 45]]
[55 35 92]


In [7]:
#Boolean indexing, numpy return only the elements where the condition is true
import numpy as np
cpu = np.array([42,55,78,91,63,88,30]) 
print(cpu>75)  # prints boolean mask / boolean array
print(cpu[cpu>75]) # filtered where condition is true
print(cpu[(cpu >=50) & (cpu <=80)]) 
print(np.where(cpu>75)) # tells only the positions, not the values and returns tuple not a plair array

[False False  True  True False  True False]
[78 91 88]
[55 78 63]
(array([2, 3, 5]),)


In [9]:
#Dataset
import numpy as np
servers = np.array([
    [55,60,78,91,85],  # cpu %'s Server A
    [30,32,35,33,31],  # server B
    [70,75,88,95,99],  # server C
])

latency = np.array([12,15,14,45,16,13,60,18]) #latency in ms 
print(f"1\n", servers[2])
print(f"2\n",servers[0,2])
print(f"3\n",servers[:,-2:])
print(f"4\n",servers[:,1])
print(f"5\n",latency[latency >20])
#######
print(f"6\n",np.where(latency >20))
print(f"6\n", np.where(latency >20)[0])

1
 [70 75 88 95 99]
2
 78
3
 [[91 85]
 [33 31]
 [95 99]]
4
 [60 32 75]
5
 [45 60]
6
 (array([3, 6]),)
6
 [3 6]
