In [3]:
#Basic math
import numpy as np
cpu = np.array([42,55,78,91,63])
print(cpu)
print(cpu + 10)
print(cpu - 50)
print(cpu *2)
print(cpu/100)

[42 55 78 91 63]
[ 52  65  88 101  73]
[-8  5 28 41 13]
[ 84 110 156 182 126]
[0.42 0.55 0.78 0.91 0.63]


In [4]:
#core aggregations - single number from an array
cpu = np.array([42,55,78,91,63])
print(np.sum(cpu))
print(np.mean(cpu))
print(np.min(cpu))
print(np.std(cpu)) # std tells you how stable the readings are. 
                   #Low std means consistent. High std means erratic — worth investigating.

329
65.8
42
17.1743995528228


In [5]:
#Axis wise aggregations - per server or per minute
servers = np.array([
                [42,55,78,91,63], #server A
                 [30,35,40,38,45],#server B
                 [88,92,95,97,99]  # server c
])
print(np.mean(servers,axis = 1)) # axis 1 - result per row per server, across all columns
print(np.mean(servers, axis =0)) 
print(np.max(servers, axis = 0)) # axis 0 is for  single columns, across all rows
print(np.mean(servers)) #global mean (for all servers)

[65.8 37.6 94.2]
[53.33333333 60.66666667 71.         75.33333333 69.        ]
[88 92 95 97 99]
65.86666666666666


In [23]:
#Dynamic threshold - mean + 2*std
cpu = np.array([60,62,58,61,63,59,92,60,61,95])
mean = np.mean(cpu)
std = np.std(cpu)
threshold = mean + 2*std
print(f"mean: {mean:.1f}")
print(f"std: {std:.1f}")
print(f"threshold: {threshold:.1f}")
print(f"spikes: {cpu[cpu > threshold]}")

mean: 67.1
std: 13.3
threshold: 93.7
spikes: [95]


In [6]:
import numpy as np
servers = np.array([   
    [55,60,78,91,85],
    [30,32,35,33,31],
    [70,75,88,95,99],
])

latency = np.array([12,15,14,45,16,13,60,18])
print("mean per server")
print(np.mean(servers, axis=1)) # 1. Print the mean CPU for each server
print("max per minute")
print(np.max(servers, axis=0)) # 2. Print the max CPU at each time step across all servers
mean = np.mean(latency)
std = np.std(latency)

print(f"mean latency: {mean:.1f}") # 3. Print the overall mean and std of latency
print(f"std latency : {std:.1f}")
threshold = mean + 2*std   # 4. Calculate dynamic threshold for latency — mean + 2 * std
print(f"threshold: {threshold:.1f}") 
print(f"spikes", latency[latency > threshold])   # 5. Print only latency values that exceed the threshold
print(latency - mean)  # 6. By how much does each latency reading differ from the mean?

mean per server
[73.8 32.2 85.4]
max per minute
[70 75 88 95 99]
mean latency: 24.1
std latency : 16.9
threshold: 57.9
spikes [60]
[-12.125  -9.125 -10.125  20.875  -8.125 -11.125  35.875  -6.125]
