In [2]:
#Boolean Logic and Filtering
#single condition
import numpy as np
cpu = np.array([42,55,78,91,63,88,30])
print(cpu >75) # F F F TT T
print(cpu[cpu>75]) # [FILTERS THE TRUE VALUES]

[False False  True  True False  True False]
[78 91 88]


In [4]:
#multiple contions AND,OR,NOT  
import numpy as np
cpu = np.array([42,55,78,91,63,88,30])
print(cpu[(cpu>60) & (cpu<90)])  #AND
print(cpu[(cpu <40) | (cpu>85)  ])  #OR
print(cpu[~(cpu>75)])  #not - inverst the condition

[78 63 88]
[91 88 30]
[42 55 63 30]


In [11]:
# np.where - positions and values together
import numpy as np
cpu = np.array([42,55,78,91,63,88,30])
print(cpu)
indx = np.where(cpu > 75)
print(indx)
print(cpu[indx])
flags = np.where(cpu>75,1,0)   #np.where with arguements - if/else on entire array, replace value with 1 else 0
print(flags)

[42 55 78 91 63 88 30]
(array([2, 3, 5]),)
[78 91 88]
[0 0 1 1 0 1 0]


In [1]:
#Applying logic across 2D arrays
# np.any — at least one reading meets the condition.
# np.all — every reading meets the condition.
import numpy as np
servers = np.array([
    [42,55,78,91,63],
    [30,35,40,38,45],
    [88,92,95,97,99],
])
print(servers)
print(servers[servers>80])
print(np.any(servers > 90, axis = 1))  # across rows, T OR F
print(np.all(servers > 40, axis =1))

[[42 55 78 91 63]
 [30 35 40 38 45]
 [88 92 95 97 99]]
[91 88 92 95 97 99]
[ True False  True]
[ True False  True]


In [4]:
# counting alerts
cpu = np.array([42,55,78,91,63,88,30])
print(np.sum(cpu))  # sum of all cpu readings
print(np.sum(cpu>75)) # sum of how many reading exceed 75 np.sum boolean array counts the trues.
print(np.mean(cpu>75) *100) # boolean array gives the proportion multiply by 100 gives percentage.

447
3
42.857142857142854


In [2]:
# All together
import numpy as np
servers = np.array([
    [55,60,78,91,85],
    [30,32,35,33,31],
    [70,75,88,95,99],

])
latency = np.array([12,15,14,45,16,13,60,18])
# 1. Print all readings across all servers above 80
print(servers[servers>80])

# 2. Print latency values that are above 20 AND below 50
print(latency[(latency >20) & (latency <50)])

# 3. Which servers have at least one reading above 90?
print(np.any(servers >90, axis=1))

# 4. Flag every latency reading — 1 if above 20ms, 0 if normal
flags = np.where(latency >20,1,0)
print(flags)

# # 5. How many latency readings exceeded 20ms?
print(np.sum(latency > 20))

# # 6. What percentage of latency readings were above 20ms?
print(f"{np.mean(latency>20)*100:.1f}%")

[91 85 88 95 99]
[45]
[ True False  True]
[0 0 0 1 0 0 1 0]
2
25.0%


In [7]:
#Dataset - 5 servers, 6 time steps for cpu_metrics
import numpy as np
cpu_metrics = np.array([
    [84, 87, 90, 83, 94, 150],   
    [78, 57, 78, 56, 89, 91],
    [56, 74, 46, 58, 69, 79],
    [87, 76, 65, 54, 94, 160],  
    [60, 62, 61, 59, 63, 64]
])
print(cpu_metrics)
print("shape", np.shape(cpu_metrics))
print("average of all server cpu readings-global", cpu_metrics.mean)
print("standard deviation of all servers-global", cpu_metrics.std)
print("average of each server", cpu_metrics.mean(axis=1))  #server wise
print("average of all servers at particular time ", cpu_metrics.mean(axis=0))  #time wise for all servers
print("high cpu among all servers", cpu_metrics.max())
print("servers with above 80 average", cpu_metrics[cpu_metrics.mean(axis=1) >80]) 
row_mean = cpu_metrics.mean(axis=1)
row_std = cpu_metrics.std(axis=1)

threshold = row_mean + 2 * row_std
anomalies = []

for i in range(len(cpu_metrics)):
    anomalies.append(cpu_metrics[i] > threshold[i])

anomalies = np.array(anomalies)
print(anomalies)

anomalies = np.array(anomalies)
servers_with_anomaly = anomalies.any(axis=1)
print("servers with anomalies:\n", cpu_metrics[servers_with_anomaly])

[[ 84  87  90  83  94 150]
 [ 78  57  78  56  89  91]
 [ 56  74  46  58  69  79]
 [ 87  76  65  54  94 160]
 [ 60  62  61  59  63  64]]
shape (5, 6)
average of all server cpu readings-global <built-in method mean of numpy.ndarray object at 0x0000027E1D917690>
standard deviation of all servers-global <built-in method std of numpy.ndarray object at 0x0000027E1D917690>
average of each server [98.         74.83333333 63.66666667 89.33333333 61.5       ]
average of all servers at particular time  [ 73.   71.2  68.   62.   81.8 108.8]
high cpu among all servers 160
servers with above 80 average [[ 84  87  90  83  94 150]
 [ 87  76  65  54  94 160]]
[[False False False False False  True]
 [False False False False False False]
 [False False False False False False]
 [False False False False False  True]
 [False False False False False False]]
servers with anomalies:
 [[ 84  87  90  83  94 150]
 [ 87  76  65  54  94 160]]


In [20]:
#Dataset - 5 servers, 6 time steps for cpu_metrics with hypothetical cpu reading above 100.
import numpy as np
cpu_metrics = np.array([
    [84, 87, 90, 83, 94, 150],   
    [78, 57, 78, 56, 89, 91],
    [56, 74, 46, 58, 69, 79],
    [87, 76, 65, 54, 94, 160],  
    [60, 62, 61, 59, 63, 64]
])
print(cpu_metrics)
print("shape", np.shape(cpu_metrics))
print("average of all server cpu readings-global\n", cpu_metrics.mean().round(2))
print("standard deviation of all servers-global\n", cpu_metrics.std().round(2))
print("average of each server\n", cpu_metrics.mean(axis=1).round(2))  #server wise
print("average of all servers at particular time \n", cpu_metrics.mean(axis=0))  #time wise for all servers
print("high cpu among all servers\n", cpu_metrics.max())
print("servers with above 80 average \n", cpu_metrics[cpu_metrics.mean(axis=1) >80]) 
row_mean = cpu_metrics.mean(axis=1)
row_std = cpu_metrics.std(axis=1)

threshold = row_mean + 2 * row_std
anomalies = cpu_metrics[ cpu_metrics > threshold[:,None]]     # same dataset [:,None] used to make broadcasting easy.
print("Anomalies", anomalies)

[[ 84  87  90  83  94 150]
 [ 78  57  78  56  89  91]
 [ 56  74  46  58  69  79]
 [ 87  76  65  54  94 160]
 [ 60  62  61  59  63  64]]
shape (5, 6)
average of all server cpu readings-global
 77.47
standard deviation of all servers-global
 24.77
average of each server
 [98.   74.83 63.67 89.33 61.5 ]
average of all servers at particular time 
 [ 73.   71.2  68.   62.   81.8 108.8]
high cpu among all servers
 160
servers with above 80 average 
 [[ 84  87  90  83  94 150]
 [ 87  76  65  54  94 160]]
Anomalies [150 160]


In [ ]:
################################################## CASE STUDY ##############################################################

In [3]:
# case study1 - Dataset 3 servers, 5 timestamps 
# Result: no anomaly detected.

import numpy as np
servers = np.array([   
    [55,60,78,91,85],
    [30,32,35,33,31],
    [70,75,88,95,99],
])

row_mean = servers.mean(axis=1)
row_std = servers.std(axis=1)
threshold = row_mean + 2 * row_std
print(threshold.round(2))
#print(servers[servers > threshold[:,None]])
anomalies = servers[servers > threshold[:, None]]
print(anomalies)

[101.84  35.64 107.84]
[]


In [4]:
#case study 2 - Dataset 3 servers, 5 timestamps , hypothetical readings set above 100
# Result: no anomalies 
import numpy as np
servers = np.array([   
    [50, 52, 49, 51, 100],   # 🔥 anomaly: 100
    [30, 31, 29, 32, 30],    # normal
    [70, 72, 71, 69, 140],   # 🔥 anomaly: 140
])
row_mean = servers.mean(axis=1)
row_std = servers.std(axis=1)
threshold = row_mean + 2 * row_std
print(threshold.round(2))
#print(servers[servers > threshold[:,None]])
anomalies = servers[servers > threshold[:, None]]
print(anomalies)

[100.05  32.44 140.04]
[]


In [6]:
#case study 3 - Dataset 3 servers, 10 timestamps, hypothetical reading set above 100.
# Result: 2 anomalies 
import numpy as np

servers = np.array([   
    [50,51,49,52,50,51,49,52,50,120],   # anomaly: 120
    [30,31,29,32,30,31,29,32,30,31],    # normal
    [70,71,69,72,70,71,69,72,70,150],   # anomaly: 150
])

# Step 1: Mean & Std
row_mean = servers.mean(axis=1)
row_std = servers.std(axis=1)

# Step 2: Dynamic threshold
threshold = row_mean + 2 * row_std
print("Threshold:", threshold.round(2))

# Step 3: Detect anomalies
anomalies = servers[servers > threshold[:, None]]
print("Anomalies:", anomalies)

Threshold: [ 99.18  32.55 126.18]
Anomalies: [120 150]


In [ ]:
# case study observation. 
# In case 1 and case 2 the readings mostly normal with 1 reading closer to 100 or above, the logic did not find any anomaly 
# because the threshold increases with increase in mean. Even though added big values (120, 130, 150, 160), 
# they are pulling the mean and std up, so the threshold also increases… and hides the anomalies. so it never detects the anomaly, 
# where as in case 3 when the timestamps increase to 10 with similar reading mostly normal and 1 or 2 readings above 100, could find the anomaly. 
# With very small datasets (like 5 points), mean + 2·std almost NEVER flags anomalies reliably. 
# Like in case 3 - We need more normal data + few spikes. Mean stays stable, Std stays controlled, Threshold stays reasonable.Spike crosses threshold

#conclusion : Don’t rely only on mean + 2*std (dynamic threshold).